### ISSUE TITLE
[PE-D][Tester D] Documentation error for Add in Command Summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-4/tp#219]
Documentation error for Add in Command Summary. The example given will not be successful.

![image.png](https://raw.githubusercontent.com/elvern18/ped/main/files/ae7eb27e-a630-45e2-9ca9-c364147164bc.png)

![image.png](https://raw.githubusercontent.com/elvern18/ped/main/files/3c59c33f-7265-48cc-aa2a-598932513b8b.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: elvern18/ped#3

**Comment by zhoyx** [comment]
Resolved
